# Processors
LATEX = latex --interaction=nonstopmode
BIBTEX = bibtex
L2H = latex2html
PDFLATEX = pdflatex
PS2PDF = ps2pdf
DVIPS = dvips
FIG2DEV = fig2dev
FIND = find
XARGS = xargs
GZIP = gzip -f
COPY = if test -r $*.toc; then cp $*.toc $*.toc.bak; fi
RM = rm -f
DOCUMENT = sistema_medicion_integral

# Viewers
PSVIEWER = gv
PDFVIEWER = acroread 

RERUN = (There were undefined references|Rerun to get (cross-references|the bars) right)
RERUNBIB = No file.*.bbl|There were undefined citations

DVIFILES = ${DOCUMENT}.dvi
GOALS = $(DVIFILES) ${DOCUMENT}.ps ${DOCUMENT}.pdf

ALLFILES =  ${DOCUMENT}.tex
IMAGEFILES = 

main:		$(IMAGEFILES) $(GOALS)

all:		$(IMAGEFILES) $(GOALS)

view:		${DOCUMENT}.pdf
		$(PDFVIEWER) ${DOCUMENT}.pdf &

%.eepic:	%.fig
		fig2dev -L eepic $< $*.eepic

%.dvi:		%.tex $(ALLFILES)
		$(COPY);$(LATEX) $<
		egrep -c "$(RERUNBIB)" $*.log && ($(BIBTEX) $*;$(COPY);$(LATEX) $<) ; true
		egrep "$(RERUN)|$(RERUNBIB)" $*.log && ($(COPY);$(LATEX) $<) ; true
		egrep "$(RERUN)|$(RERUNBIB)" $*.log && ($(COPY);$(LATEX) $<) ; true
		if cmp -s $*.toc $*.toc.bak; then echo "OK" ;else $(LATEX) $< ; fi
		$(RM) $*.toc.bak

%.ps:		%.dvi
		dvips $< -o $@
		cp $@ $@.copy
		$(GZIP) $@
		mv $@.copy $@

%.pdf:		%.ps
		cp $< $<.copy
		$(PS2PDF) $<
		mv $<.copy $<

clean: 		
		($(FIND) ./ \
		    -maxdepth 1 \
		    -name "*.aux" -or \
		    -name "*.log" -or \
		    -name "*.bbl" -or \
		    -name "*.blg" -or \
		    -name "*.brf" -or \
		    -name "*.cb" -or \
		    -name "*.ind" -or \
		    -name "*.idx" -or \
		    -name "*.ilg" -or \
		    -name "*.inx" -or \
		    -name "*.ps" -or \
		    -name "*.dvi" -or \
		    -name "*.pdf" -or \
		    -name "*.ps.gz" -or \
		    -name "*.thm" -or \
		    -name "*.toc" -or \
		    -name "*.bak" -or \
		    -name "*.out" -or \
		    -name "*~*" -or \
		    -name "*.eepic" \
		) | $(XARGS) $(RM)

cleaner:
		make clean
		$(RM) Makefile

