This is makeindex, version 2.15 [TeX Live 2009] (kpathsea + Thai support).
Scanning style file ./tesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file tesis.acn....done (327 entries accepted, 0 rejected).
Sorting entries.....done (2943 comparisons).
Generating output file tesis.acr....done (243 lines written, 0 warnings).
Output written in tesis.acr.
Transcript written in tesis.alg.
