This is makeindex, version 2.15 [TeX Live 2009] (kpathsea + Thai support).
Scanning style file ./Embedded_system_design.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Embedded_system_design.acn....done (70 entries accepted, 0 rejected).
Sorting entries....done (460 comparisons).
Generating output file Embedded_system_design.acr....done (117 lines written, 0 warnings).
Output written in Embedded_system_design.acr.
Transcript written in Embedded_system_design.alg.
