#
# TransFig makefile
#

all: elastic_blob.tex 

# translation into gif

elastic_blob.gif: elastic_blob.fig Makefile
	fig2dev -L gif elastic_blob.fig elastic_blob.gif
clean::
	rm -f elastic_blob.tex

